import type { Metadata } from "next";

export type Page = {
  id: string;
  title: string;
  href: string;
};

export const PAGES: Page[] = [
  { id: "achievements", title: "今までの実績", href: "/achievements" },
  { id: "university", title: "大学時代でのエピソード", href: "/university" },
  { id: "highschool", title: "高校時代でのエピソード", href: "/highschool" },
  { id: "tools", title: "このサイトに使用したツール", href: "/tools" },
];

export const SITE_METADATA: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
