import type { Metadata } from "next";

export type Page = {
  id: string;
  title: string;
  href: string;
};

export const PAGES: Page[] = [
  { id: "journey", title: "自己PR", href: "/journey" },
  { id: "game", title: "ゲーム公開で得た経験", href: "/game" },
  { id: "music", title: "音楽制作による制作物", href: "/music" },
  { id: "hackathon", title: "ハッカソンで得た経験", href: "/hackathon" },
  { id: "internship", title: "インターンで得た経験", href: "/internship" },
  { id: "challenges", title: "その他、挑戦や失敗経験", href: "/challenges" },
];

export const SITE_METADATA: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
